import type { EnhancedImgAttributes } from "@sveltejs/enhanced-img";

/**
 * Type of an enhanced image source, generated by the `@sveltejs/enhanced-img` plugin.
 */
export type EnhancedImgSrc = EnhancedImgAttributes["src"];

/**
 * Element type of an array.

 * @template T - The array type.
 */
export type ElementOf<T> = T extends (infer E)[] ? E : never;
